# Google Cloud Build configuration
# Usage: gcloud builds submit --config=cloudbuild.yaml
#
# IMPORTANT: Before deploying, create secrets in Secret Manager:
#   gcloud secrets create DATABASE_URL --data-file=-
#   gcloud secrets create CLOUDINARY_API_KEY --data-file=-
#   gcloud secrets create CLOUDINARY_API_SECRET --data-file=-
#   gcloud secrets create ADMIN_PASSWORD --data-file=-
#   gcloud secrets create SEED_SECRET_TOKEN --data-file=-

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/al-khair:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/al-khair:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/al-khair'
    id: 'push-image'

  # Deploy to Cloud Run with secure configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'al-khair'
      - '--image'
      - 'gcr.io/$PROJECT_ID/al-khair:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      # Resource limits to prevent abuse detection
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '30s'
      # CPU only allocated during request processing
      - '--cpu-throttling'
      # Use Secret Manager for sensitive values (create secrets first!)
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest,CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest,ADMIN_PASSWORD=ADMIN_PASSWORD:latest,SEED_SECRET_TOKEN=SEED_SECRET_TOKEN:latest'
      # Non-sensitive environment variables
      - '--set-env-vars'
      - 'NODE_ENV=production,CLOUDINARY_CLOUD_NAME=dlsobyta0'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/al-khair:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/al-khair:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
